#!/usr/bin/env bash

# Prints out tree of yadm/git tracked files

help() {
    self_name=$(basename "$0")
    if [ -n "$1" ]; then
        >&2 echo
        >&2 echo "$self_name -- Prints tree of files tracked with yadm/git"
        >&2 echo "usage: $self_name [--root tree_root_name] <tree command options>"
        exit 1
    else
        echo "$self_name -- Prints tree of files tracked with yadm/git"
        echo "usage: $self_name [--root tree_root_name] <tree command options>"
        exit 0
    fi
}

require() {
    command -v "$1" 1>/dev/null || { >&2 echo "Error: $1 is not installed";exit 1; }
}

require git
require tree

PARAMS=()
while (( "$#" )); do
  case "$1" in
    --help) help;shift;;
    --root) ROOT="$2";shift;shift;;
    *) PARAMS+=("$1");shift;;
  esac
done
set -- "${PARAMS[@]}"

out="$(eval "$([[ -d "${PWD}/.git" ]] && command -v git || command -v yadm)" ls-files | tree --fromfile "${PARAMS[@]}")" || help 'err'
if [[ -n "$ROOT" ]]; then
    out="$(sed "1s/.*/$ROOT/" <<< "$out")"
fi
printf %s "$out"
