#!/usr/bin/env bash

# Bonds all the wlan and eth interfaces (except wlan0) and creates a hotspot in wlan0
# Prequisites: Add 'net.ifnames=0' to the kernel parameters so udev allocate devices with traditional wlan0, wlan1...

: ${BOND_NAME:=merge-bond}
: ${LOCAL_GATEWAY:=192.168.24.1}

if [[ $EUID -ne 0 ]]; then
  >&2 echo "This script must be run as root"
  exit 1
fi

ip link delete $BOND_NAME 2>/dev/null || true

if [[ $1 = '--reset' ]]; then
    # Restart the interfaces after bond deletion (cuz by default it becomes off)
    for ifc in $(ip -o link show | awk -F': ' '$2 ~ /wlan|eth/ {print $2}'); do
        ip link set $ifc down
        ip link set $ifc up
    done
else
    # Create a virtual bond master interface and slave all except wlan0
    ip link add $BOND_NAME type bond
    ip link set $BOND_NAME down

    for ifc in $(ip -o link show | awk -F': ' '$2 ~ /wlan|eth/ && $2 !~ /wlan0/ {print $2}'); do
        ip link set $ifc down
        ip link set $ifc master $BOND_NAME
        ip link set $ifc up
    done

    ip link set $BOND_NAME up

    # Create AP on wlan0
    iw phy phy0 interface add ap0 type __ap
    ip addr add $LOCAL_GATEWAY dev ap0

    cat > /etc/hostapd/hostapd.conf <<EOF
interface=ap0
driver=nl80211
ssid=IIITL-507
channel=7
hw_mode=g
wme_enabled=1
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=3
wpa_passphrase=iiitl@1234
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
EOF

    cat > /etc/dnsmasq.conf <<EOF
# disables dnsmasq reading any other files like /etc/resolv.conf for nameservers
no-resolv
no-dhcp-interface=lo,wlan0

interface=ap0
domain-needed
bogus-priv
server=8.8.8.8
${LOCAL_GATEWAY/.*/.50}
dhcp-range=${LOCAL_GATEWAY/.*/.50},${LOCAL_GATEWAY/.*/.50},12h
dhcp-option=3,$LOCAL_GATEWAY
EOF

    hostapd hostapd.conf
fi

