#!/usr/bin/env bash

# Bonds all the wlan and eth interfaces and creates a hotspot
# Prequisites: Add 'net.ifnames=0' to the kernel parameters so udev allocate devices with traditional wlan0, wlan1...

: ${BOND_NAME:=merge-bond}

if [[ $EUID -ne 0 ]]; then
  >&2 echo "This script must be run as root"
  exit 1
fi

ip link delete $BOND_NAME 2>/dev/null || true
ip link add $BOND_NAME type bond
ip link set $BOND_NAME down

for ifc in $(ip -o link show | awk -F': ' '$2 ~ /wlan|eth/{print $2}'); do
    ip link set $ifc down
    ip link set $ifc master $BOND_NAME
    ip link set $ifc up
done

ip link set $BOND_NAME up
