#!/usr/bin/env bash

# Arranges the files by grouping them into folder of their extension name

require() {
    command -v "$1" 1>/dev/null || { >&2 echo "Error: $1 is not installed";exit 1; }
}

require fd
require egrep

declare -A special_cases=(
    ['^*.(tar.*|tbz)$']='tar'
)

fd -tf -d1 \
| while read file; do
    folder="$PWD/${file##*.}"
    for regex in "${!special_cases[@]}"; do
        (echo "$file" | egrep -q "$regex") && {
            folder="$PWD/${special_cases[$regex]}"
            break
        }
    done

    mkdir -p "$folder"
    mv "$file" "$folder"
done
