#!/usr/bin/env bash

# Counts lines of code in a git repository
# Source: https://stackoverflow.com/a/29012789/11377112

require() {
    command -v "$1" 1>/dev/null || { >&2 echo "Error: $1 is not installed";exit 1; }
}

require git
require cloc

git clone --depth 1 "$1" /tmp/temp-linecount-repo &&
  printf "('/tmp/temp-linecount-repo' will be deleted automatically)\n\n\n" &&
  cloc /tmp/temp-linecount-repo &&
  rm -rf /tmp/temp-linecount-repo

