#!/usr/bin/env bash

# Copies the text from anywhere on the screen to clipboard using tesseract-ocr

require() {
    command -v "$1" 1>/dev/null || { >&2 echo "Error: $1 is not installed";exit 1; }
}

require maim
require xclip
require tesseract-ocr

IMAGE_FILE="/tmp/ocr.png"

maim -s "$IMAGE_FILE" \
&& tesseract-ocr "$IMAGE_FILE" - 2> /dev/null | sed 's/\x0c//' | xclip -sel clip \
&& rm "$IMAGE_FILE"
