#!/usr/bin/env bash

# Finds and appends pwd of currently focused window using EWMH to the given command

ARGS=("$@")
fallback() {
    exec "${ARGS[@]}"
}
require_or_fallback() {
    command -v "$1" 1>/dev/null || { >&2 echo "Error: $1 is not installed"; fallback; }
}

require_or_fallback pgrep
require_or_fallback readlink

pid_script="${0%/*}/active-window-pid"
[[ -x "$pid_script" ]] || fallback

pid=$($pid_script)
[[ -n "$pid" ]] || fallback

child_pid=$(pgrep -P "$pid" | tail -n1)
[[ -n "$child_pid" ]] && child_pwd=$(readlink -f "/proc/$child_pid/cwd") || child_pwd=$(readlink -f "/proc/$pid/cwd") || fallback

exec "$@" "$child_pwd"
