#!/usr/bin/env bash

# Setup raspberry pi as a wifi-repeater (Ext-Dongle: client, Inbuilt: AP)
# Prequisites: Mount Pi's root and boot partitions to $1 and $1/boot respectively

if [[ $# -ne 4 ]]; then
    >&2 echo "Usage: $(basename $0) <rpi-mount-point> <wifi-ssid> <wifi-passwd> <ap-ssid> <ap-passwd>"
    exit 1
fi

if [[ ! -x "$1/usr/bin" ]]; then
    static_chroot_bin=$(which qemu-aarch64-static) || {
        echo "Install package providing qemu-aarch64-static (protip: use xlocate in void)";
        exit 1;
    }
    sudo cp $static_chroot_bin "$1/usr/bin"
fi

../snips/xc "$1" <<<EOF

# Remove classic networking
systemctl disable ifupdown dhcpcd dhcpcd5 isc-dhcp-client isc-dhcp-common rsyslog
apt --autoremove purge ifupdown dhcpcd dhcpcd5 isc-dhcp-client isc-dhcp-common rsyslog
rm -r /etc/network /etc/dhcp

# Setup systemd-networkd
systemctl disable avahi-daemon libnss-mdns
apt --autoremove purge avahi-daemon
apt install libnss-resolve
ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
apt-mark hold avahi-daemon dhcpcd dhcpcd5 ifupdown isc-dhcp-client isc-dhcp-common libnss-mdns openresolv raspberrypi-net-mods rsyslog
systemctl enable systemd-networkd.service systemd-resolved.service


# Setup wlan0 as AP
cat > /etc/wpa_supplicant/wpa_supplicant-wlan0.conf <<EOSF
country=IN
ctrl_interface=DIR=/run/wpa_supplicant GROUP=netdev
update_config=1
p2p_disabled=1

network={
    ssid="$4"
    mode=2
    key_mgmt=WPA-PSK
    psk="$5"
    frequency=2412
}
EOSF

chmod 600 /etc/wpa_supplicant/wpa_supplicant-wlan0.conf
systemctl disable wpa_supplicant.service
systemctl enable wpa_supplicant@wlan0.service
rfkill unblock wlan

# Setup wlan1 as client
cat > /etc/wpa_supplicant/wpa_supplicant-wlan1.conf <<EOSF
country=IN
ctrl_interface=DIR=/run/wpa_supplicant GROUP=netdev
update_config=1
p2p_disabled=1

network={
    ssid="$2"
    psk="$3"
}
EOSF

chmod 600 /etc/wpa_supplicant/wpa_supplicant-wlan1.conf
systemctl disable wpa_supplicant.service
systemctl enable wpa_supplicant@wlan1.service


# Configure interfaces
cat > /etc/systemd/network/08-wlan0.network <<EOSF
[Match]
Name=wlan0
[Network]
Address=192.168.4.1/24
LLMNR=no
DNSSEC=no
MulticastDNS=yes
# IPMasquerade is doing NAT
IPMasquerade=yes
IPForward=yes
DHCPServer=yes
[DHCPServer]
DNS=84.200.69.80 1.1.1.1
EOSF

cat > /etc/systemd/network/12-wlan1.network <<EOSF
[Match]
Name=wlan1
[Network]
LLMNR=no
DNSSEC=no
MulticastDNS=yes
DHCP=yes
EOSF

EOF

