#!/bin/sh

# Puts laptop into s2idle(1h), deep-sleep(2h), and into hibernation if still no activity

s2idle_sleep_time=3600  # 1 hour
deep_sleep_time=7200    # 2 hour

sleep_until() {
    start_time=$(date +%s)
    rtcwake -u -s "$1" -m mem 1>/dev/null
    end_time=$(date +%s)

    echo $(( end_time - start_time + 2 ))
}

original_sleep=$(cat /sys/power/mem_sleep | awk -F '[][]' '{print $2}')

echo s2idle > /sys/power/mem_sleep
if [ $(sleep_until $s2idle_sleep_time) -gt $s2idle_sleep_time ]; then
    echo deep > /sys/power/mem_sleep
    if [ $(sleep_until $deep_sleep_time) -gt $deep_sleep_time ]; then
        ZZZ
    fi
fi

echo "$original_sleep" > /sys/power/mem_sleep
