#!/bin/sh

# Records screen using ffmpeg (saves file with name if provided)
# Source: Somewhere in the r/unixporn community.

resolution=$(xdpyinfo | awk '/dimensions/ {print $2}')

if [ "$1" ]; then
  filename="$1"
else
  filename="$(date).mp4"
fi
ffmpeg \
    -video_size "$resolution"\
    -framerate 35 \
    -f x11grab \
    -i :0.0 \
    -pix_fmt yuv420p \
    -c:v libx264 \
    -preset ultrafast \
    -y \
    -v error \
    -stats \
    "$filename"

